export const Metadata = {
  Keyname: "Typing",
  Title: "Typing Division",
  Desc: "Divides the Platform into 26 data type categories.",
  Child: [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ],
  System: ["Typology"],
};
export const Index = {
  Typing: {
    A: null,
    B: { Keyname: "Boolean", Desc: "Represents true or false" },
    C: { Keyname: "Coloring", Desc: "Represents color data" },
    D: { Keyname: "Dating", Desc: "Represents the date & time" },
    E: { Keyname: "Entity", Desc: "Represents software entities" },
    F: { Keyname: "File", Desc: "Represents digital files" },
    G: { Keyname: "Graphic", Desc: "Represents graphical formats" },
    H: { Keyname: "Hyperlink", Desc: "Represents virtual locations" },
    I: { Keyname: "Index", Desc: "Represents sets of data" },
    J: null,
    K: { Keyname: "Keycode", Desc: "Represents unique codes" },
    L: null,
    M: { Keyname: "Media", Desc: "Represents media files" },
    N: { Keyname: "Numeral", Desc: "Represents number data" },
    O: { Keyname: "Operation", Desc: "Represents programming operations" },
    P: { Keyname: "Part", Desc: "Represents UI component parts" },
    Q: { Keyname: "Equation", Desc: "Represents mathematic equations" },
    R: { Keyname: "Rule", Desc: "Represents programming logic" },
    S: { Keyname: "Structure", Desc: "Represents data structures" },
    T: { Keyname: "Textual", Desc: "Represents text data" },
    U: null,
    V: { Keyname: "Value", Desc: "Represents values of data" },
    W: { Keyname: "Window", Desc: "Represents UI windows/tabs" },
    X: { Keyname: "Coordinate", Desc: "Represents positions in space" },
    Y: null,
    Z: null,
  },
};
